version: "3.5"

services:
  php_fpm:
      build: .
      container_name: pulseai_nginx_phpfpm
      working_dir: /usr/share/nginx/pulseai_app
      networks:
        - pulseai_app
      volumes:
          - ./:/usr/share/nginx/pulseai_app
  nginx:
      image: nginx:1.15
      container_name: pulseai_app_nginx
      working_dir: /usr/share/nginx/pulseai_app
      networks:
        - pulseai_app
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/pulseai_app
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
      image: mysql:5.7
      container_name: pulseai_app_mysql
      networks:
        - pulseai_app
      environment:
        - MYSQL_DATABASE=pulseai_app
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=pulseai
        - MYSQL_PASSWORD=password

networks:
  pulseai_app:
    driver: bridge
